"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { Header } from "@/components/header";
import { useCart } from "@/components/cart-provider";
import { createClient } from "@/lib/supabase/client";
import { Address } from "@/lib/types";

export default function Checkout(){
 const {items,subtotal,clear}=useCart();const [form,setForm]=useState({name:"",phone:"",line1:"",city:"Chennai",state:"Tamil Nadu",pincode:""});const [addresses,setAddresses]=useState<Address[]>([]);const [selected,setSelected]=useState("");const [msg,setMsg]=useState("");const r=useRouter();const delivery=subtotal>=999?0:60;
 useEffect(()=>{(async()=>{const s=createClient();if(!s)return;const {data:{user}}=await s.auth.getUser();if(!user)return;const {data}=await s.from("addresses").select("*").eq("user_id",user.id).order("is_default",{ascending:false});if(data?.length){setAddresses(data as Address[]);choose(data[0] as Address)}})()},[]);
 function choose(a:Address){setSelected(a.id);setForm({name:a.recipient_name,phone:a.phone,line1:[a.line1,a.line2].filter(Boolean).join(", "),city:a.city,state:a.state,pincode:a.pincode})}
 async function place(e:React.FormEvent){e.preventDefault();if(!items.length)return;const s=createClient();if(!s){const no=`AP-${Math.floor(1000+Math.random()*9000)}`;localStorage.setItem("demo-last-order",JSON.stringify({no,total:subtotal+delivery,form,items}));clear();setMsg(`Order ${no} placed in demo mode.`);setTimeout(()=>r.push("/account"),700);return}const {data:{user}}=await s.auth.getUser();if(!user){setMsg("Please login before placing a live order.");return}const orderNo=`AP-${Date.now().toString().slice(-6)}`;const {data:order,error}=await s.from("orders").insert({user_id:user.id,order_number:orderNo,status:"placed",subtotal,delivery_fee:delivery,total:subtotal+delivery,shipping_address:form}).select().single();if(error||!order){setMsg(error?.message||"Could not create order");return}const rows=items.map(i=>({order_id:order.id,product_id:i.id,product_name:i.name,quantity:i.quantity,unit_price:i.price,line_total:i.price*i.quantity}));const {error:itemError}=await s.from("order_items").insert(rows);if(itemError){setMsg(itemError.message);return}clear();r.push("/account")}
 return <><Header/><main className="shell section"><div className="page-head"><span className="kicker red">CHECKOUT</span><h1>Delivery details</h1></div><div className="cart-layout"><form className="panel form-grid" onSubmit={place}>{addresses.length>0&&<div className="span2 saved-address-picker"><b>Saved addresses</b>{addresses.map(a=><button type="button" key={a.id} className={selected===a.id?"saved-address active":"saved-address"} onClick={()=>choose(a)}><span>✓</span><div><strong>{a.label}{a.is_default?" · Default":""}</strong><small>{a.recipient_name} · {a.line1}, {a.city} {a.pincode}</small></div></button>)}</div>}<label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="span2">Address<input required value={form.line1} onChange={e=>setForm({...form,line1:e.target.value})}/></label><label>City<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input required value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>Pincode<input required pattern="[0-9]{6}" value={form.pincode} onChange={e=>setForm({...form,pincode:e.target.value})}/></label><div></div><button className="btn btn-primary span2">Place order — ₹{subtotal+delivery}</button>{msg&&<p className="notice span2">{msg}</p>}</form><aside className="panel summary"><h2>Your items</h2>{items.map(i=><div key={i.id}><span>{i.name} × {i.quantity}</span><b>₹{i.price*i.quantity}</b></div>)}<hr/><div><span>Delivery</span><b>{delivery?`₹${delivery}`:"FREE"}</b></div><div className="total"><span>Total</span><b>₹{subtotal+delivery}</b></div><small>Prototype checkout: no payment gateway is connected yet.</small></aside></div></main></>}
