import Link from "next/link";
import { Header } from "@/components/header";
import { ProductGrid } from "@/components/product-grid";
export default function Home(){return <><Header/><main>
<section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="kicker">FROM OUR HOME TO YOURS</span><h1>Pure traditional foods for a healthier tomorrow.</h1><p>Small-batch ghee, ready mixes, podis and pantry favourites made with familiar ingredients and recipes that feel like home.</p><div className="hero-actions"><Link className="btn btn-primary" href="/shop">Shop the pantry →</Link><a className="btn btn-ghost" href="#story">Our story</a></div><div className="trust-row"><span>✓ No preservatives</span><span>✓ Traditional recipes</span><span>✓ Freshly prepared</span></div></div><div className="hero-scene"><div className="kolam">✦ ❋ ✦</div><div className="brass">🪔</div><div className="jar">🫙</div><div className="spices">🌶️ 🥣 🌿</div><p>Good food.<br/>Brighter days.</p></div></div></section>
<section className="shell section"><div className="section-heading"><div><span className="kicker red">OUR BESTSELLERS</span><h2>Featured products</h2></div><Link href="/shop">View all products →</Link></div><ProductGrid featuredOnly/></section>
<section id="story" className="story"><div className="shell story-grid"><div className="story-art">🌴 🏡 🌾<br/><span>👩🏽‍🍳 🫕</span></div><div><span className="kicker">ROOTED IN HOME COOKING</span><h2>Bringing traditional goodness to modern homes.</h2><p>Our concept is built around dependable everyday foods: honest ingredients, familiar flavours, useful pack sizes and a modern ordering experience without losing the warmth of an Indian kitchen.</p><div className="four-values"><span>🌿<b>Pure ingredients</b></span><span>🔥<b>Traditional recipes</b></span><span>🚫<b>No artificial preservatives</b></span><span>🤝<b>Local sourcing</b></span></div></div></div></section>
<section className="shell section"><div className="section-heading"><div><span className="kicker red">THE PROTOTYPE</span><h2>Already built beyond a static mockup.</h2></div></div><div className="feature-cards"><article><b>👤 Customer accounts</b><p>Email login/signup with Supabase Auth when connected.</p></article><article><b>🛒 Cart & checkout</b><p>Persistent cart, address capture and order creation.</p></article><article><b>📦 Admin operations</b><p>Manage products, inventory, orders and customer visibility.</p></article></div></section>
</main><footer><div className="shell footer-grid"><div><b>🪷 Amma&apos;s Pantry</b><p>Tradition in every bite.</p></div><div><b>Explore</b><Link href="/shop">Products</Link><Link href="/login">My account</Link></div><div><b>Prototype</b><Link href="/admin">Admin dashboard</Link><span>Made with ❤️ in India</span></div></div></footer></>}
