import Link from "next/link";
import { Header } from "@/components/header";
import { ProductGrid } from "@/components/product-grid";
export default function Home(){return <><Header/><main>
<section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="kicker">FROM OUR HOME TO YOURS</span><h1>Traditional goodness for your family.</h1><p>Small-batch ghee, ready mixes, podis and pantry favourites made with familiar ingredients and recipes that feel like home.</p><div className="hero-actions"><Link className="btn btn-primary" href="/shop">Shop the pantry →</Link><a className="btn btn-ghost" href="#story">Our story</a></div><div className="trust-row"><span>✓ No preservatives</span><span>✓ Traditional recipes</span><span>✓ Freshly prepared</span></div></div><div className="hero-photo"><img src="/products/pure-cow-ghee-detail.jpg" alt="Amma's Pantry pure cow ghee"/><div className="hero-photo-copy"><small>HOUSE FAVOURITE</small><b>Pure Cow Ghee</b><span>Traditional · aromatic · golden</span></div></div></div></section>
<section className="shell section"><div className="section-heading"><div><span className="kicker red">OUR BESTSELLERS</span><h2>Featured products</h2></div><Link href="/shop">View all products →</Link></div><ProductGrid featuredOnly/></section>
<section id="story" className="story"><div className="shell story-grid"><div className="story-art">🌴 🏡 🌾<br/><span>👩🏽‍🍳 🫕</span></div><div><span className="kicker">ROOTED IN HOME COOKING</span><h2>Bringing traditional goodness to modern homes.</h2><p>Our concept is built around dependable everyday foods: honest ingredients, familiar flavours, useful pack sizes and a modern ordering experience without losing the warmth of an Indian kitchen.</p><div className="four-values"><span>🌿<b>Pure ingredients</b></span><span>🔥<b>Traditional recipes</b></span><span>🚫<b>No artificial preservatives</b></span><span>🤝<b>Local sourcing</b></span></div></div></div></section>
<section className="shell section"><div className="section-heading"><div><span className="kicker red">BUILT FOR A REAL SHOP</span><h2>From product upload to customer order.</h2></div></div><div className="feature-cards"><article><b>📷 Product management</b><p>Upload product photos, control stock, prices, featured items and visibility.</p></article><article><b>🛒 Customer journey</b><p>Product pages, persistent cart, saved addresses, checkout and order history.</p></article><article><b>📦 Shop operations</b><p>Live dashboard, fulfilment statuses, low-stock visibility and customer spend.</p></article></div></section>
</main><footer><div className="shell footer-grid"><div><b>🪷 Amma&apos;s Pantry</b><p>Tradition in every bite.</p></div><div><b>Explore</b><Link href="/shop">Products</Link><Link href="/login">My account</Link></div><div><b>Prototype</b><Link href="/admin">Admin dashboard</Link><span>Made with ❤️ in India</span></div></div></footer></>}
