"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { demoOrders,demoProducts } from "@/lib/demo-data";
import { Order,Product } from "@/lib/types";
export default function Admin(){
 const [orders,setOrders]=useState<Order[]>(demoOrders);const [products,setProducts]=useState<Product[]>(demoProducts);const [customers,setCustomers]=useState(143);const [live,setLive]=useState(false);
 useEffect(()=>{(async()=>{const s=createClient();if(!s)return;const [{data:o},{data:p},{count}]=await Promise.all([s.from("orders").select("id,order_number,status,total,created_at,profiles(full_name)").order("created_at",{ascending:false}).limit(6),s.from("products").select("*"),s.from("profiles").select("id",{count:"exact",head:true}).eq("role","customer")]);if(o)setOrders(o.map((x:any)=>({...x,customer_name:x.profiles?.full_name||"Customer"})));if(p)setProducts(p as Product[]);if(typeof count==="number")setCustomers(count);setLive(true)})()},[]);
 const revenue=orders.filter(o=>o.status!=="cancelled").reduce((s,o)=>s+Number(o.total),0);const low=products.filter(p=>p.stock<15);
 return <><div className="admin-title"><div><p>Operations overview</p><h1>Good evening 👋</h1></div><span className={live?"mode live":"mode"}>{live?"● Live dashboard":"● Demo dashboard"}</span></div><div className="stats"><article><span>Recent orders</span><b>{orders.length}</b><small>Latest visible orders</small></article><article><span>Revenue</span><b>₹{revenue.toLocaleString("en-IN")}</b><small>From loaded orders</small></article><article><span>Customers</span><b>{customers}</b><small>Registered customers</small></article><article><span>Low stock</span><b>{low.length}</b><small>Below 15 units</small></article></div><div className="admin-grid"><section className="panel"><h2>Recent orders</h2>{orders.map(o=><div className="order-line" key={o.id}><div><b>{o.order_number}</b><small>{o.customer_name}</small></div><span className="status-pill green">{o.status}</span><strong>₹{Number(o.total).toLocaleString("en-IN")}</strong></div>)}</section><section className="panel"><h2>Low-stock pulse</h2>{(low.length?low:products.slice().sort((a,b)=>a.stock-b.stock).slice(0,5)).map(p=><div className="inventory-line" key={p.id}>{p.image_url?<img className="inventory-thumb" src={p.image_url} alt=""/>:<span>{p.image_emoji}</span>}<div className="grow"><b>{p.name}</b><div className="meter"><i style={{width:`${Math.min(100,p.stock*3)}%`}}/></div></div><strong>{p.stock}</strong></div>)}</section></div></>
}
