"use client";
import { useEffect, useState } from "react";
import { demoProducts } from "@/lib/demo-data";
import { Product } from "@/lib/types";
import { createClient } from "@/lib/supabase/client";

const blank={name:"",slug:"",description:"",category:"Ready Mixes",price:0,unit:"250 g",stock:0,featured:false,active:true,image_emoji:"🥣"};
export function AdminProducts(){
 const [products,setProducts]=useState<Product[]>(demoProducts); const [form,setForm]=useState(blank); const [message,setMessage]=useState(""); const [isLive,setIsLive]=useState(false);
 useEffect(()=>{(async()=>{const s=createClient(); if(!s)return; const {data}=await s.from("products").select("*").order("created_at",{ascending:false}); if(data){setProducts(data as Product[]);setIsLive(true)}})()},[]);
 async function addProduct(e:React.FormEvent){e.preventDefault(); const item={...form,id:crypto.randomUUID(),compare_at_price:null}; const s=createClient(); if(s){const {data,error}=await s.from("products").insert(form).select().single(); if(error){setMessage(error.message);return} setProducts(x=>[data as Product,...x]);setMessage("Product added to Supabase.");}else{setProducts(x=>[item as Product,...x]);setMessage("Added in demo mode. Connect Supabase to persist it.");} setForm(blank);}
 async function toggle(p:Product){ const s=createClient(); if(s) await s.from("products").update({active:!p.active}).eq("id",p.id); setProducts(x=>x.map(i=>i.id===p.id?{...i,active:!i.active}:i)); }
 return <><div className="admin-title"><div><p>Catalog management</p><h1>Products</h1></div><span className={isLive?"mode live":"mode"}>{isLive?"● Live database":"● Demo mode"}</span></div>
 <div className="admin-split"><form className="panel form-grid" onSubmit={addProduct}><h2>Add a product</h2><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-")})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Ghee & Oils</option><option>Ready Mixes</option><option>Podis & Spices</option><option>Snacks</option><option>Pantry</option><option>Gift Hampers</option></select></label><label>Price ₹<input type="number" min="1" required value={form.price||""} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>Unit<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label>Stock<input type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)})}/></label><label>Emoji / icon<input value={form.image_emoji} onChange={e=>setForm({...form,image_emoji:e.target.value})}/></label><label className="span2">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn btn-primary span2">Save product</button>{message&&<p className="notice span2">{message}</p>}</form>
 <div className="panel"><h2>Inventory</h2><div className="table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.image_emoji} {p.name}</b><small>{p.unit}</small></td><td>₹{p.price}</td><td>{p.stock}</td><td><button className={p.active?"status-pill green":"status-pill"} onClick={()=>toggle(p)}>{p.active?"Active":"Hidden"}</button></td></tr>)}</tbody></table></div></div></div></>
}
