"use client";
import { useEffect, useRef, useState } from "react";
import { demoProducts } from "@/lib/demo-data";
import { Product } from "@/lib/types";
import { createClient } from "@/lib/supabase/client";

const blank={name:"",slug:"",description:"",category:"Ready Mixes",price:0,compare_at_price:null as number|null,unit:"250 g",stock:0,featured:false,active:true,image_emoji:"🥣",image_url:""};
type FormState=typeof blank & {id?:string};
export function AdminProducts(){
 const [products,setProducts]=useState<Product[]>(demoProducts); const [form,setForm]=useState<FormState>(blank); const [message,setMessage]=useState(""); const [isLive,setIsLive]=useState(false); const [uploading,setUploading]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 async function refresh(){const s=createClient();if(!s)return;const {data}=await s.from("products").select("*").order("created_at",{ascending:false});if(data){setProducts(data as Product[]);setIsLive(true)}}
 useEffect(()=>{refresh()},[]);
 function edit(p:Product){setForm({...p,image_url:p.image_url||"",compare_at_price:p.compare_at_price||null});setMessage("Editing product. Save to apply changes.");window.scrollTo({top:0,behavior:"smooth"})}
 async function upload(file:File){
   if(!file.type.startsWith("image/")){setMessage("Please choose an image file.");return}
   const s=createClient();
   if(!s){setForm(f=>({...f,image_url:URL.createObjectURL(file)}));setMessage("Photo preview added in demo mode. Connect Supabase Storage to persist uploads.");return}
   setUploading(true);setMessage("Uploading photo…");
   const ext=file.name.split(".").pop()?.toLowerCase()||"jpg"; const safe=(form.slug||form.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")||"product"); const path=`${safe}-${Date.now()}.${ext}`;
   const {error}=await s.storage.from("product-images").upload(path,file,{cacheControl:"3600",upsert:false});
   if(error){setUploading(false);setMessage(error.message+" — run the Stage 3.5 migration if the bucket is not created yet.");return}
   const {data}=s.storage.from("product-images").getPublicUrl(path); setForm(f=>({...f,image_url:data.publicUrl}));setUploading(false);setMessage("Photo uploaded. Save the product to publish it.");
 }
 async function saveProduct(e:React.FormEvent){e.preventDefault();setMessage("");const s=createClient();const payload={name:form.name,slug:form.slug,description:form.description,category:form.category,price:form.price,compare_at_price:form.compare_at_price||null,unit:form.unit,stock:form.stock,featured:form.featured,active:form.active,image_emoji:form.image_emoji,image_url:form.image_url||null};
   if(s){if(form.id){const {error}=await s.from("products").update(payload).eq("id",form.id);if(error){setMessage(error.message);return}}else{const {error}=await s.from("products").insert(payload);if(error){setMessage(error.message);return}}await refresh();setMessage(form.id?"Product updated successfully.":"Product added to Supabase.");}
   else{if(form.id)setProducts(x=>x.map(p=>p.id===form.id?{...p,...payload} as Product:p));else setProducts(x=>[{...payload,id:crypto.randomUUID()} as Product,...x]);setMessage("Saved in demo mode only.")}
   setForm(blank);
 }
 async function toggle(p:Product){const s=createClient();if(s)await s.from("products").update({active:!p.active}).eq("id",p.id);setProducts(x=>x.map(i=>i.id===p.id?{...i,active:!i.active}:i));}
 async function remove(p:Product){if(!confirm(`Delete ${p.name}?`))return;const s=createClient();if(s){const {error}=await s.from("products").delete().eq("id",p.id);if(error){setMessage(error.message);return}}setProducts(x=>x.filter(i=>i.id!==p.id));if(form.id===p.id)setForm(blank);setMessage("Product deleted.")}
 return <><div className="admin-title"><div><p>Catalog & inventory</p><h1>Products</h1></div><span className={isLive?"mode live":"mode"}>{isLive?"● Live database":"● Demo mode"}</span></div>
 <div className="admin-split"><form className="panel form-grid" onSubmit={saveProduct}><div className="span2 form-title-row"><h2>{form.id?"Edit product":"Add a product"}</h2>{form.id&&<button type="button" className="text-btn" onClick={()=>setForm(blank)}>Cancel edit</button>}</div><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:form.id?form.slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Ghee & Oils</option><option>Ready Mixes</option><option>Podis & Spices</option><option>Snacks</option><option>Pantry</option><option>Gift Hampers</option></select></label><label>Price ₹<input type="number" min="1" required value={form.price||""} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>MRP ₹<input type="number" min="0" value={form.compare_at_price||""} onChange={e=>setForm({...form,compare_at_price:e.target.value?Number(e.target.value):null})}/></label><label>Pack size<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label>Stock quantity<input type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)})}/></label><label className="span2">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="span2 upload-box"><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><div className="upload-preview">{form.image_url?<img src={form.image_url} alt="Product preview"/>:<span>📷</span>}</div><div><b>Product photo</b><p>PNG, JPG or WEBP · recommended square image</p><button type="button" className="btn btn-ghost" disabled={uploading} onClick={()=>fileRef.current?.click()}>{uploading?"Uploading…":form.image_url?"Change photo":"Upload photo"}</button></div></div><label className="check-row"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><label className="check-row"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><button className="btn btn-primary span2">{form.id?"Save changes":"Save product"}</button>{message&&<p className="notice span2">{message}</p>}</form>
 <div className="panel"><h2>Inventory</h2><div className="table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><div className="admin-product-cell">{p.image_url?<img src={p.image_url} alt=""/>:<span>{p.image_emoji}</span>}<div><b>{p.name}</b><small>{p.unit}</small></div></div></td><td>₹{p.price}</td><td><span className={p.stock<15?"low-stock-text":""}>{p.stock}</span></td><td><button className={p.active?"status-pill green":"status-pill"} onClick={()=>toggle(p)}>{p.active?"Active":"Hidden"}</button></td><td><div className="table-actions"><button onClick={()=>edit(p)}>Edit</button><button className="danger" onClick={()=>remove(p)}>Delete</button></div></td></tr>)}</tbody></table></div></div></div></>
}
