"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Header } from "@/components/header";
import { createClient } from "@/lib/supabase/client";
import { demoOrders } from "@/lib/demo-data";
import { Address,Order } from "@/lib/types";

const emptyAddress={label:"Home",recipient_name:"",phone:"",line1:"",line2:"",city:"Chennai",state:"Tamil Nadu",pincode:"",is_default:true};
export default function Account(){
 const [name,setName]=useState("Demo Customer"); const [email,setEmail]=useState("demo@example.com"); const [orders,setOrders]=useState<Order[]>(demoOrders.slice(0,3)); const [addresses,setAddresses]=useState<Address[]>([]);const [addressForm,setAddressForm]=useState(emptyAddress);const [showAddress,setShowAddress]=useState(false);const [msg,setMsg]=useState("");const [live,setLive]=useState(false); const router=useRouter();
 async function load(){const s=createClient();if(!s){try{const u=JSON.parse(localStorage.getItem("demo-user")||"{}");if(u.full_name)setName(u.full_name);if(u.email)setEmail(u.email)}catch{}return}const {data:{user}}=await s.auth.getUser();if(!user){router.replace("/login");return}setLive(true);setEmail(user.email||"");const [{data:profile},{data:o},{data:a}]=await Promise.all([s.from("profiles").select("full_name").eq("id",user.id).single(),s.from("orders").select("id,order_number,status,total,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(12),s.from("addresses").select("*").eq("user_id",user.id).order("is_default",{ascending:false})]);setName(profile?.full_name||user.user_metadata?.full_name||"Customer");if(o)setOrders(o as Order[]);if(a)setAddresses(a as Address[])}
 useEffect(()=>{load()},[router]);
 async function saveAddress(e:React.FormEvent){e.preventDefault();const s=createClient();if(!s){setMsg("Address saved only in live mode.");return}const {data:{user}}=await s.auth.getUser();if(!user)return;if(addressForm.is_default)await s.from("addresses").update({is_default:false}).eq("user_id",user.id);const {error}=await s.from("addresses").insert({...addressForm,user_id:user.id});if(error){setMsg(error.message);return}setAddressForm(emptyAddress);setShowAddress(false);setMsg("Address saved.");await load()}
 async function removeAddress(id:string){const s=createClient();if(!s)return;await s.from("addresses").delete().eq("id",id);setAddresses(x=>x.filter(a=>a.id!==id))}
 async function logout(){const s=createClient();if(s)await s.auth.signOut();else localStorage.removeItem("demo-user");router.push("/")}
 return <><Header/><main className="shell section"><div className="account-head"><div><span className="kicker red">MY ACCOUNT</span><h1>Namaste, {name.split(" ")[0]} 👋</h1><p>{email} · {live?"Live account":"Demo account"}</p></div><div className="hero-actions"><Link className="btn btn-ghost" href="/shop">Continue shopping</Link><button className="btn btn-ghost" onClick={logout}>Logout</button></div></div><div className="dashboard-grid"><section className="panel"><h2>My orders</h2>{orders.length?orders.map(o=><div className="order-line" key={o.id}><div><b>{o.order_number}</b><small>{new Date(o.created_at).toLocaleDateString("en-IN")}</small></div><span className="status-pill green">{o.status}</span><strong>₹{Number(o.total).toLocaleString("en-IN")}</strong></div>):<p>No orders yet.</p>}</section><section className="panel"><div className="panel-title-row"><h2>Saved addresses</h2><button className="text-btn" onClick={()=>setShowAddress(v=>!v)}>+ Add address</button></div>{addresses.length?addresses.map(a=><div className="address-card" key={a.id}><div><b>{a.label}{a.is_default?" · Default":""}</b><p>{a.recipient_name}<br/>{a.line1}{a.line2?`, ${a.line2}`:""}<br/>{a.city}, {a.state} {a.pincode}<br/>{a.phone}</p></div><button className="text-btn" onClick={()=>removeAddress(a.id)}>Delete</button></div>):<p>{live?"No saved addresses yet.":"Connect Supabase to save reusable addresses."}</p>}{showAddress&&<form className="address-form" onSubmit={saveAddress}><input placeholder="Recipient name" required value={addressForm.recipient_name} onChange={e=>setAddressForm({...addressForm,recipient_name:e.target.value})}/><input placeholder="Phone" required value={addressForm.phone} onChange={e=>setAddressForm({...addressForm,phone:e.target.value})}/><input placeholder="Address line" required value={addressForm.line1} onChange={e=>setAddressForm({...addressForm,line1:e.target.value})}/><div className="two-inputs"><input placeholder="City" required value={addressForm.city} onChange={e=>setAddressForm({...addressForm,city:e.target.value})}/><input placeholder="Pincode" required value={addressForm.pincode} onChange={e=>setAddressForm({...addressForm,pincode:e.target.value})}/></div><button className="btn btn-primary full">Save address</button></form>}{msg&&<p className="notice">{msg}</p>}</section></div></main></>
}
